Repository OpenVR-Advanced-Settings/OpenVR-AdvancedSettings, pull requests merged in 2019-01, with the labels that each got.

#39 Refactor OverlayController to be implemented as RAII object instead of global singleton
  src/main.cpp
  src/overlaycontroller.cpp
  src/overlaycontroller.h
  src/tabcontrollers/ReviveTabController.cpp
Labels: refactor

#57 Refactor OpenVR init code to separate class
  advancedSettings.pro
  src/overlaycontroller.cpp
  src/overlaycontroller.h
  src/overlaycontroller/openvr_init.cpp
  src/overlaycontroller/openvr_init.h
Labels: refactor

#58 fixed default audio profile display
  src/res/qml/AudioPage.qml
  src/tabcontrollers/AudioTabController.cpp
  src/tabcontrollers/AudioTabController.h
Labels: bug, refactor

#59 Add IVRInput bindings for media keys
  Readme.md
  advancedSettings.pro
  installer/installer.nsi
  src/ivrinput/ivrinput.cpp
  src/ivrinput/ivrinput.h
  src/ivrinput/ivrinput_action.h
  src/ivrinput/ivrinput_action_set.h
  src/ivrinput/ivrinput_manifest.h
  src/main.cpp
  src/overlaycontroller.cpp
  src/overlaycontroller.h
  src/overlaycontroller/openvr_init.cpp
  src/overlaycontroller/openvr_init.h
  src/package_files/action_manifest.json
  src/package_files/bindingsinterface.bat
  src/package_files/default_action_manifests/vive_defaults.json
Labels: enhancement

#61 Add Alt+Enter button to keyboard keys
  docs/screenshots/UtilitiesPage.png
  src/res/qml/UtilitiesPage.qml
  src/tabcontrollers/KeyboardInput.h
  src/tabcontrollers/UtilitiesTabController.cpp
  src/tabcontrollers/UtilitiesTabController.h
  src/tabcontrollers/keyboardinput/KeyboardInputDummy.cpp
  src/tabcontrollers/keyboardinput/KeyboardInputDummy.h
  src/tabcontrollers/keyboardinput/KeyboardInputWindows.cpp
  src/tabcontrollers/keyboardinput/KeyboardInputWindows.h
Labels: enhancement

#64 Update Travis CI to use clang in addition to g++, update readme, update standard to C++17
  .travis.yml
  Readme.md
  advancedSettings.pro
Labels: bug, enhancement

#69 Move the utilities page QML into its own folder and extract components
  advancedSettings.pro
  src/res/qml/RootPage.qml
  src/res/qml/UtilitiesPage.qml
  src/res/qml/mainwidget.qml
  src/res/qml/utilities_page/UtilitiesPage.qml
  src/res/qml/utilities_page/alarm_clock/AlarmGroupBox.qml
  src/res/qml/utilities_page/desktop_size/SteamDesktopGroupBox.qml
  src/res/qml/utilities_page/keyboard_utils/KeyboardGroupBox.qml
  src/res/qml/utilities_page/media_keys/MediaButton.qml
  src/res/qml/utilities_page/media_keys/MediaControllerKeys.qml
  src/res/qml/utilities_page/media_keys/outline_play_pause_white_24dp.svg
  src/res/qml/utilities_page/media_keys/outline_skip_next_white_24dp.svg
  src/res/qml/utilities_page/media_keys/outline_skip_previous_white_24dp.svg
  src/res/qml/utilities_page/media_keys/outline_stop_white_24dp.svg
Labels: refactor
