Repository OpenVR-Advanced-Settings/OpenVR-AdvancedSettings, pull requests merged in 2020-06, with the labels that each got.

#466 Refactor alarm system and replace notification method
  build_scripts/qt/resources.pri
  build_scripts/qt/sources.pri
  docs/screenshots/UtilitiesPage.png
  src/alarm_clock/vr_alarm.cpp
  src/alarm_clock/vr_alarm.h
  src/overlaycontroller.cpp
  src/overlaycontroller.h
  src/res/img/alarm/alarm_activated.png
  src/res/qml/common/HourComboBox.qml
  src/res/qml/common/MinuteSecondComboBox.qml
  src/res/qml/common/TimeAssembly.qml
  src/res/qml/utilities_page/alarm_clock/AlarmGroupBox.qml
  src/settings/internal/settings_controller.h
  src/settings/settings.h
  src/tabcontrollers/UtilitiesTabController.cpp
  src/tabcontrollers/UtilitiesTabController.h
Labels: bug

#468 Refactor update rates of tab controllers
  build_scripts/qt/sources.pri
  src/alarm_clock/vr_alarm.cpp
  src/overlaycontroller.cpp
  src/overlaycontroller.h
  src/tabcontrollers/AudioTabController.cpp
  src/tabcontrollers/AudioTabController.h
  src/tabcontrollers/ChaperoneTabController.cpp
  src/tabcontrollers/ChaperoneTabController.h
  src/tabcontrollers/MoveCenterTabController.cpp
  src/tabcontrollers/MoveCenterTabController.h
  src/tabcontrollers/SettingsTabController.cpp
  src/tabcontrollers/SettingsTabController.h
  src/tabcontrollers/SteamVRTabController.cpp
  src/tabcontrollers/SteamVRTabController.h
  src/tabcontrollers/UtilitiesTabController.cpp
  src/tabcontrollers/UtilitiesTabController.h
  src/tabcontrollers/VideoTabController.cpp
  src/utils/update_rate.cpp
  src/utils/update_rate.h
Labels: refactor

#484 Disallow AppImageLauncher integration
  build_scripts/linux/appimage.sh
Labels: Linux
