Repository OpenVR-Advanced-Settings/OpenVR-AdvancedSettings, pull requests merged in 2020-03, with the labels that each got.

#367 Add push to mute icon when using push to mute feature
  src/res/img/audio/microphone/ptm_notification.png
  src/tabcontrollers/AudioTabController.cpp
  src/tabcontrollers/AudioTabController.h
Labels: enhancement

#380 Updated Manifest
  src/overlaycontroller.cpp
  src/overlaycontroller.h
  src/package_files/manifest.vrmanifest
Labels: Breaking Change

#382 Fix push to mute icon not being used when PTM enabled
  src/tabcontrollers/AudioTabController.cpp
Labels: bug
